---
- hosts: appservers
  become: yes

  vars:
    username: flask
    app_name: testounet
    app_entrypoint: app
    flask_app: ..

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: basic apps present
      apt:
        name: 
          - python3-dev
          - python3-pip
          - python3-virtualenv
          - virtualenv
          - nginx
          - rsync
        state: present

    - name: "add the user {{username}}"
      user:
        name: "{{username}}"
        state: present
        append: yes
        groups:
          - "www-data"

    - name: copy app files
      synchronize:
        src: "{{ flask_app }}" 
        dest: /home/{{ username }}/{{ app_name }}
        perms: no

    - name: install modules in a virtualenv
      pip:
        requirements: /home/{{ username }}/{{ app_name }}/requirements.txt
        virtualenv: /home/{{ username }}/{{ app_name }}/venv
        virtualenv_python: python3

    - name: change permissions of app directory
      file:
        path: /home/{{ username }}/{{ app_name }}
        state: directory
        owner: "{{ username }}"
        recurse: true

    - name: template systemd service config
      template:
        src: templates/app.service.j2
        dest: /etc/systemd/system/{{ app_name }}.service

    - name: start systemd app service
      systemd:
        name: "{{ app_name }}.service"
        state: restarted
        enabled: yes

    - name: template nginx site config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}.conf

    - name: remove default nginx site config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: enable nginx site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: yes

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes


